project/discussions/routes.py
from flask import  render_template, url_for, Blueprint, session, request, escape, redirect, flash
from project.models import db,User, QuestionThreads, Tags, DTags, Answers, AnswerVotes, TagsFollowing, QFollowing
from project.discussions.forms import QuestionForm, AnswerForm
from sqlalchemy import and_

discussions=Blueprint('discussions',__name__)

@discussions.route('/hello/')
def temp():
	return render_template('FormLayout.html')

@discussions.route('/QuestionsPage/')
def QuesPage():
	if "user_id" in session.keys():
		present_user=db.session.query(User).get(session['user_id'])
		Tags=present_user.user_tags()
		return render_template("QuesPage.html",Tags=Tags)
	else:
		return "ACCESS DENIED"


@discussions.route('/questions',methods=['POST'])
def questions():
	if request.method=="POST":
		if 'option' in request.form.keys():
			option=int(request.form['option'])
			if option==1:
				curr_user=db.session.query(User).get(int(session['user_id']))
				user_questions=curr_user.questions_asked()
				if user_questions==None:
					user_questions=[]
				return render_template("questions.html",questions=user_questions,OnlyOne=False,tag_limit=None,len=len,str=str)
			elif option==2:
				curr_user=db.session.query(User).get(int(session['user_id']))
				user_tags=curr_user.user_tags()
				questions=curr_user.user_follows()
				if questions==None:
					questions=[]
				return render_template("questions.html",questions=questions,OnlyOne=False,tag_limit=None)
			elif option==3:
				tag_id=int(escape(request.form['tag_id']))
				if tag_id!=None:
					tag=db.session.query(Tags).get(int(tag_id))
					questions=tag.get_questions()
				else:
					questions=[]
				return render_template("questions.html",questions=questions,OnlyOne=False,tag_limit=None)
			
			elif option==4:
				allQuestions=db.session.query(QuestionThreads).order_by(QuestionThreads.Qdate.desc()).all()
				return render_template("questions.html",questions=allQuestions,OnlyOne=False,tag_limit=None)
			else:
				return "Explore..."


@discussions.route('/AnswersPage')
def answerPage():
	if "user_id" in session.keys():
		present_user=db.session.query(User).get(session['user_id'])
		Tags=present_user.user_tags()
		Qid=request.args.get('Qid')
		question=db.session.query(QuestionThreads).get(int(Qid))
		present_user_following=False
		if int(Qid) in [x.Qid for x in present_user.user_follows()]:
			present_user_following=True
		answers=question.get_answers()
		return render_template("AnswersPage.html",Tags=Tags,question=question, answers=answers,len=len, present_user_following=present_user_following)
	else:
		return "ACCESS DENIED"



@discussions.route('/AskQuestion/',methods=['POST','GET'])
def askQuestion():
	if ('username' in session.keys()) and ('user_id' in session.keys()):
		if (request.method=='POST') and ('QSubmit' in request.form.keys()):
			Qauthor=int(session['user_id'])
			Qtitle=escape(request.form['Qtitle'])
			QDescription=escape(request.form['Qdescription'])
			QAnonymous=int(request.form['QAnonymous'])
			new_question=QuestionThreads(Qauthor=Qauthor,Qtitle=Qtitle,QDescription=QDescription, QAnonymous=QAnonymous )

			db.session.add(new_question)
			db.session.commit()

			Qtags=list(escape(request.form['QTags']).split())
			
			for tag in Qtags:
				if tag[0]=='#':
					tag_id=db.session.query(Tags.Tagid).filter(Tags.Tagtitle==tag).first()
					if tag_id ==None:
						new_tag=Tags(Tagtitle=tag)
						db.session.add(new_tag)
						db.session.commit()
						tag_id=new_tag

					new_QuesTag=DTags(Tag=tag_id.Tagid,Discussion=new_question.Qid)
					db.session.add(new_QuesTag)
					db.session.commit()
			
			return redirect(url_for('users.homepage'))

		elif request.method=='GET':
			form=QuestionForm()
			return render_template('questionForm.html',form=form)
	else:
		return 'ACCESS DENIED'



@discussions.route('/answerQuestion', methods=['POST','GET'])
def answerQ():
	if "user_id" in session.keys():
		if request.method=="POST":
			Aauthor=int(session['user_id'])
			Atitle=escape(request.form['Atitle'])
			Aans=escape(request.form['AContent'])
			AQid=escape(request.form['answeringTo'])
			new_answer=Answers(Aauthor=Aauthor,Atitle=Atitle,Aans=Aans, AQid=AQid)
			db.session.add(new_answer)
			db.session.commit()
			return redirect(url_for('users.homepage'))
		else:
			form=AnswerForm()
			Qid=int(escape(request.args.get('Qid')))
			if Qid==None:
				return "Not Permitted"
			return render_template("AnswerForm.html", form=form, Qid=Qid)
	else:
		"ACCESS DENIED"



@discussions.route('/reactBlog/',methods=['POST'])
def reactToPost():
	if request.method=="POST":
		if ('Aid' in request.form.keys()):
			previous=db.session.query(AnswerVotes).filter(and_(AnswerVotes.user==int(session['user_id']),AnswerVotes.answer==int(request.form['Aid']) )).first()
			if previous!=None: 
				db.session.delete(previous)
				db.session.commit()
			else:
				post_vote=AnswerVotes(user=int(session['user_id']),vote=1,answer=int(request.form['Aid']))
				db.session.add(post_vote)
				db.session.commit()
			answer=db.session.query(Answers).get(int(request.form['Aid']))
		votes=list(answer.get_upvoters())
		return str(len(votes))
	else:
		pass


@discussions.route('/TagPage')
def TagInfo():
	if "user_id" in session.keys():
		tag_id=escape(request.args.get('tag_id'))
		if tag_id.isdigit():
			TAG=db.session.query(Tags).get(int(tag_id))
			present_user_following=False
			if "user_id" in session.keys():
				if session['user_id'] in [x.TFuserId for x in TAG.getFollowedBy()]:
					present_user_following=True
			return render_template("TagInfo.html", TAG=TAG, present_user_following=present_user_following )
		else:
			return "ACCESS DENIED"
	else:
		return "ACCESS DENIED"

@discussions.route('/tagFollowToggle',methods=['POST','GET'])
def tagFollowToggle():
	tagId=escape(request.args.get('tagId'))
	if ('user_id' in session.keys()) and ('username' in session.keys()):
		if request.method=='POST':
			tag_id=request.form['tagId']
			tag_id=escape(tag_id)
			TagF=db.session.query(TagsFollowing).filter(and_(TagsFollowing.TFuserId==session['user_id'], TagsFollowing.TFtagId==tag_id)).first()
			if TagF==None:
				TagF=TagsFollowing(TFuserId=session['user_id'], TFtagId=tag_id)
				db.session.add(TagF)
				db.session.commit()
			else:
				db.session.delete(TagF)
				db.session.commit()
			return redirect(url_for('discussions.tagFollowToggle', tagId=tag_id))
		else:
			tag_id=escape(tagId)
			TagF=db.session.query(TagsFollowing).filter(and_(TagsFollowing.TFuserId==session['user_id'], TagsFollowing.TFtagId==tag_id)).first()
			if TagF==None:
				return "FOLLOW"
			else:
				return "UNFOLLOW"


@discussions.route('/followDiscussion',methods=['POST','GET'])
def followDiscussion():
	Qid=escape(request.args.get('Qid'))
	if ('user_id' in session.keys()) and ('username' in session.keys()):
		if request.method=='POST':
			Qid=request.form['Qid']
			Qid=escape(Qid)
			DF=db.session.query(QFollowing).filter(and_(QFollowing.user_id==session['user_id'], QFollowing.Question==Qid)).first()
			if DF==None:
				DF=QFollowing(user_id=session['user_id'], Question=Qid)
				db.session.add(DF)
				db.session.commit()
			else:
				db.session.delete(DF)
				db.session.commit()
			return redirect(url_for('discussions.followDiscussion', Qid=Qid))
		else:
			Qid=escape(Qid)
			DF=db.session.query(QFollowing).filter(and_(QFollowing.user_id==session['user_id'], QFollowing.Question==Qid)).first()
			if DF==None:
				return "FOLLOW"
			else:
				return "UNFOLLOW"

@discussions.route('/fetchTags',methods=['POST'])
def fetchTags():
	if ('user_id' in session.keys()) and ('username' in session.keys()):
	
		if request.method=="POST":
			tagTitle=escape(request.form['tagname'])
			if tagTitle=="":
				flash("Tag Not Found...")
				return redirect(url_for('users.homepage'))
			tag=db.session.query(Tags).filter(Tags.Tagtitle==tagTitle).first()
			if tag==None:
				flash("Tag Not Found...")
				return redirect(url_for('users.homepage'))

			return redirect(url_for('discussions.TagInfo', tag_id=tag.Tagid))


@discussions.route("/allQuestions")
def AllQuestions():
	if "user_id" in session.keys():
		present_user=db.session.query(User).get(session['user_id'])
		Tags=present_user.user_tags()
		return render_template("AllQuestions.html",Tags=Tags)
	else:
		return "ACCESS DENIED"

project/users/routes.py
from datetime import datetime, date
from flask import  render_template, url_for, Blueprint, request, session, redirect, escape, flash, abort
from sqlalchemy import and_
from project.users.forms import RegisterForm, LoginForm, ChangePasswordForm, UpdateAccountForm
from project.models import db,User

users=Blueprint('users',__name__)


branches={1:"CSE",2:"ECE",3:"IT",4:"MECH",5:"CIVIL",6:"CHEM",7:"BIO-TECH",8:"PROD",9:"MCA",10:"MBA"}

@users.route('/<string:userName>/')
def profile(userName):
	if('username' in  session.keys()) and ('user_id' in session.keys()):
		present_user=db.session.query(User).get(session['user_id'])
		user = User.query.filter_by(Uusername=userName).first()
		questionAsked = user.questions_asked()
		following = user.user_follows()
		
		return render_template('profile.html',current_user=present_user,user=user,
								branches=branches, questionAsked=questionAsked, following=following) 	
	else:
		return redirect(url_for('users.login'))

@users.route('/questionAsked')
def questionAsked():
	return render_template('askedquestions.html')
	


@users.route("/login/",methods=['POST','GET'])
def login():
	if request.method=="POST":
		username=escape(request.form['Username'])
		password=escape(request.form['Password'])
		row=db.session.query(User).filter(and_(User.Uusername==username, User.Upassword==password)).first()
		if row!=None:
			session['username']=str(username)
			session['user_id']=int(row.Uid)
			return redirect(url_for('users.mainpage'))
		else:
			flash("Username or Password incorrect...")
			return redirect(url_for('users.login'))
	else:
		form=LoginForm()
		return render_template("Login.html",form=form)

@users.route('/logout/')
def logout():
	if 'username' in session.keys():
		session.pop('username')
		session.pop('user_id')
		return redirect(url_for('users.mainpage'))
	else:
		abort(401)

@users.route('/register/',methods=['POST','GET'])
def register():
	if (request.method=="POST") and ( 'Submit' in request.form.keys()):
		FirstName=escape(request.form['FirstName'])
		LastName=escape(request.form['LastName'])
		if(LastName==''):
			LastName=None
		UserName=escape(request.form['UserName'])
		UserEmail=escape(request.form['UserEmail'])
		UserDob=(datetime.strptime(escape(request.form['UserDob']),"%Y-%m-%d")).date()
		Password=escape(request.form['Password'])
		UserDescritpion=escape(request.form['UserDescritpion'])
		UserBranch=int(escape(request.form['UserBranch']))
		UserAccountType=int(escape(request.form['UserAccountType']))
		UserYear=0
		if UserAccountType!=1:
			UserYear=int(escape(request.form["UserYear"]))

		new_user=User(UfirstName=FirstName, UlastName=LastName, Uusername=UserName,Uemail=UserEmail, Udob=UserDob, UDescription=UserDescritpion, UstudyYear=UserYear, URole=UserAccountType,Upassword=Password, UBranch=UserBranch)
		db.session.add(new_user)
		db.session.commit()
		return redirect(url_for('users.login'))
	else:
		form=RegisterForm()
		return render_template("register.html",form=form)



@users.route('/update-account/',methods=['POST','GET'])
def UpdateAccount():

	if 'username' in session.keys():

		if (request.method=='POST') and ('Submit' in request.form.keys()):

			current_user = User.query.filter_by(Uid=session['user_id']).first()
			current_user.UfirstName=escape(request.form['FirstName'])
			current_user.UlastName=escape(request.form['LastName'])
			if(current_user.UlastName==''):
				current_user.UlastName=None
			current_user.Uusername=escape(request.form['UserName'])
			current_user.Uemail=escape(request.form['UserEmail'])
			current_user.Udescription=escape(request.form['UserDescription'])
			db.session.commit()

			if(current_user.Uusername==session['username']):
				return redirect(url_for('users.mainpage'))
			else:
				return redirect(url_for('users.logout'))

		elif(request.method=='GET'):
			form=UpdateAccountForm()
			current_user=User.query.filter_by(Uid=session['user_id']).first()
			print(current_user)
			form.FirstName.data = current_user.UfirstName
			form.LastName.data = current_user.UlastName
			form.UserName.data = current_user.Uusername
			form.UserEmail.data = current_user.Uemail
			form.UserDescription.data = current_user.UDescription

			return render_template('UpdateAccount.html',user=current_user,form=form)
	else:
		return redirect(url_for('users.login'))




@users.route("/change-password/",methods=['POST','GET'])
def ChangePassword():
	
	if 'username' in session.keys():	
		if (request.method=="POST") and ( 'Submit' in request.form.keys()):

			currentPassword=escape(request.form['currentPassword'])
			newPassword=escape(request.form['newPassword'])
			newPassword1=escape(request.form['reEnterPassword'])
			user = User.query.filter_by(Uid = session['user_id']).first()

			if(newPassword==newPassword1 and currentPassword==user.Upassword):
				user.Upassword = newPassword
				db.session.commit()
				return redirect(url_for('users.homepage'))
			elif(currentPassword!=user.Upassword):
				flash("Current Password did not match")
				return redirect(url_for('users.ChangePassword'))
			else:
				flash("New passwords does not match. Please check again")
				return redirect(url_for('users.ChangePassword'))
		else:
			form=ChangePasswordForm()
			return render_template("ChangePassword.html",form=form)
	else:
		return redirect(url_for('users.login'))




@users.route("/")
def mainpage():
	if ('username' in session.keys()) and ('user_id' in session.keys()):
		return redirect(url_for('users.homepage'))

	return redirect(url_for('users.login'))


@users.route('/home/')
def homepage():
	if ('username' in session.keys()) and ('user_id' in session.keys()):
		present_user=db.session.query(User).get(session['user_id'])
		Tags=present_user.user_tags()
		return render_template("homepage.html",Tags=Tags)
		
	return redirect(url_for('users.login'))

@users.route('/Account')
def Account():
	if('username' in  session.keys()) and ('user_id' in session.keys()):
		present_user=db.session.query(User).get(session['user_id'])
		return render_template('userAccount.html',current_user=present_user,branches=branches) 	

	return redirect(url_for('users.login'))

@users.route('/DeleteUser/',methods=(['POST']))
def DeleteUser():

	if 'username' in session.keys():	
		if (request.method=="POST"):
			user =  db.session.query(User).get(session['user_id'])
			db.session.delete(user)
			db.session.commit()
			return redirect(url_for('users.logout'))
		else:
			pass
	else:
		abort(401)

project/templates/AllQuestions.html
{% extends "layout.html" %}
{% block mainSection %}
<section class="container">
	<h2>Questions By All Users:</h2>
	<div class="row" id="QuesSection" >
	
	</div>


</section>

{% endblock mainSection %}

{% block scripts %}
<script type="text/javascript">
	function loadQues(Ovalue=4) {
		
		var ques = new XMLHttpRequest();

		ques.onreadystatechange = function() {
		if (this.readyState == 4 && this.status == 200) {
		document.getElementById("QuesSection").innerHTML = this.responseText;
		}
		};
		ques.open("POST", "{{url_for('discussions.questions')}}", true);
		ques.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ques.send("option="+Ovalue);
	}

	

</script>
<script type="text/javascript">
	$(document).ready(function(){
		var navElement=document.getElementById("ExplorePage");
		navElement.style.color="#FFFF33";

		//loading blogs...
		loadQues();
   	});
</script>


</script>
{% endblock scripts %}

project/templates/AnswersPage.html
{% extends "layout.html" %}
{% block mainSection %}
<section class="container">

	
	<div class="row" id="answersSection" >
		<article id="post-{{question.Qid}}" class="col-12 col-sm-12 col-md-12 rounded-lg bg-white p-3 m-2" >
			<span class="ProfileInfo rounded-pill bg-secondary p-2 text-center">
				{% if question.QAnonymous==0 %}
				<a href="{{url_for('users.profile',userName=question.get_author().Uusername)}}" class="userNameLink">
				<strong>{{question.get_author().Uusername}}</strong>
				</a>
				{% else %}
				<strong>Anonymous</strong>
				{% endif %}
			</span>
			&nbsp;
			<span >
				<small class="text-muted">{{question.Qdate.date()}}</small>
			</span>
			<hr />
			<a class="text-info" href="{{url_for('discussions.answerPage',Qid=question.Qid)}}"><p class="QuestionHeader" style="font-size: 130%;"><strong>{{question.Qtitle}}</strong></p></a>
			<p>{{question.QDescription}}...</p>
			{% with Tags=question.get_tags(tag_limit) %}
				{% if Tags %}
					<small>
					<br />
					{% for tag in Tags %}
						<a href="{{url_for('users.homepage',tag_id=tag.Tagid)}}" target="_blank">{{tag.Tagtitle}}</a>&nbsp;
					{% endfor %}
					</small>
				{% endif %}
			<br />
			{% endwith %}
			<hr />
			<a href="{{url_for('discussions.answerQ',Qid=question.Qid)}}" target="_blank"class="btn btn-success" >Answer this Question</a>
			<span style="float: right;">
			{% if present_user_following %}
				<button class="btn btn-primary  mb-3" onclick="javascript: followToggle({{question.Qid}});" id="Q-{{question.Qid}}">UNFOLLOW</button>
			{% else %}
				<button class="btn btn-primary mb-3" onclick="javascript: followToggle({{question.Qid}});" id="Q-{{question.Qid}}">FOLLOW</button>
			{% endif %}
			</span>
		</article>
		<p style="font-size: 150%;font-weight: bold;" >Answers:</p>
		<hr/>
		{% for answer in answers %}
		<article id="answer-{{answer.Aid}}" class="col-12 col-sm-12 col-md-12 rounded-lg bg-white p-3 m-2" >
			<span class="ProfileInfo rounded-pill bg-secondary p-2">
				<a href="{{url_for('users.profile',userName=answer.get_author().Uusername)}}" class="userNameLink">
				<strong>{{answer.get_author().Uusername}}</strong>
				</a>
			</span>

			&nbsp;
			<span >
				<small class="text-muted">{{answer.Adate.date()}}</small>
			</span>
			<hr />

			
			<!-- Content Section -->
			<p class="answerHeader"><strong>{{answer.Atitle}}</strong></p>
			<p>{{answer.Aans}}</p>

			<hr />

		
			<!-- Reactions Section -->
			{% with up_list= answer.get_upvoters()%}

			{% if session['user_id'] in up_list %}
				<button id="L{{answer.Aid}}"onclick="react({{answer.Aid}},1)" class="btn bg-dark text-success rounded-pill likeDislike" >&#128077;{{up_list|length}}</button>
			{% else %}
				<button id="L{{answer.Aid}}" onclick="react({{answer.Aid}},0)" class="btn text-success  rounded-pill likeDislike" >&#128077;{{len(up_list)}}</button>
			{% endif %}
			
			{% endwith %}	
		</article>
	{% endfor %}

	</div>

	{% if answers|length ==0 %}
	<div class="col-12 col-sm-12 col-md-12 rounded-lg bg-white p-3 m-2" >
	<p>Nothing To Show...</p>
	</div>
	{% endif %}

</section>

{% endblock mainSection %}

{% block scripts %}
<script type="text/javascript">
	

	function react(answer,v){
	var send_react=new XMLHttpRequest();
	send_react.onreadystatechange=function(){
		if(this.readyState==4 && this.status==200){
			document.getElementById('L'+answer).innerHTML="&#128077;"+this.responseText;
			document.getElementById('L'+answer).classList.toggle('bg-dark');
			// if (v==1){
			// 	document.getElementById('L'+answer).classList.remove('bg-dark');
			// }
			// else{
			// 	document.getElementById('L'+answer).classList.add('bg-dark');
			// }
		}
	};

	send_react.open("POST","{{url_for('discussions.reactToPost')}}",true);
	send_react.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	send_react.send("Aid="+answer);


	}


	function followToggle(Qid){
		var send_Toggle=new XMLHttpRequest();
		send_Toggle.onreadystatechange=function(){
			if(this.readyState==4 && this.status==200){
				document.getElementById('Q-'+Qid).innerHTML=this.responseText;
			}
		};

		send_Toggle.open("POST","{{url_for('discussions.followDiscussion')}}", true);
		send_Toggle.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		send_Toggle.send('Qid='+Qid);
	}

</script>
<script type="text/javascript">
	$(document).ready(function(){
		var navElement=document.getElementById("FeedPage");
		navElement.style.color="#FFFF33";

   	});
</script>

<script type="text/javascript">
	function copyToClipBoard(postId){
		
		var link_string="http://localhost:5000/Detailblog/"+postId;
		navigator.clipboard.writeText(link_string).then(function(){ alert("Link Copied...");}, function(){alert("Link not copied...");})
		return false;
	}


</script>
{% endblock scripts %}

project/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='style.css')}}">

    <title>CBIT Stack-Overflow</title>
  </head>
  <body>
    <header class="mb-2 sticky-top bg-light">
        
        <nav class="navbar navbar-light shadow sticky-top navbar-expand-sm ">
          <div class="container-fluid">

            
            <div class="navbar-header" >
                <div class="navbar-brand"><a href="{{url_for('users.homepage')}}"><h1 class="text-center" >CBIT Stack-Overflow</h1></a></div>
            </div>


            <!--Collapse Navbar-->
            {% if "username" in session.keys() %}
            <div class="collapse navbar-collapse" id="navbarToggler1" >
              <ul class="nav navbar-nav navbar-right ml-auto" >
                <li ><a href="{{url_for('discussions.QuesPage')}}" id="FeedPage" class=" mx-1">Discussions</a></li>
                <li ><a href="{{url_for('discussions.AllQuestions')}}" id="ExplorePage" class=" mx-1">Explore</a></li>
                <!-- <li><a href="#" id="DiscussionPage" class=" mx-1">Link3</a></li> -->
               <!--  <li><a href="#" id="SearchPage" class="nav-link mx-1"><i class="fa fa-search"></i>Search</a></li>
              </ul> -->
            </div>

            <!-- Profile Pic -->
            <div class="dropdown nav-item ml-auto"  >
                  <a href="#" class="nav-link dropdown-toggle " data-toggle="dropdown">
                     <img src="{{url_for('static',filename='profile/temp_pic.jpg')}}" alt="profile" style="width: 2em;height: 2em;border-radius: 40%">
                  </a>
                  <div class="dropdown-menu dropdown-menu-right  " style="width: 50%;">
                          <p class="dropdown-header text-center" ><strong> {{session['username']}}</strong></p>
                          
                          <a class="dropdown-item text-center" href="{{url_for('users.profile',userName=session['username'])}}">Profile</a>
                          <a class="dropdown-item text-center" href="{{url_for('users.Account')}}">Account</a>
                          <a class="dropdown-item text-center" href="{{url_for('users.logout')}}">Logout</a>
                  </div>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler1" aria-controls="navbarToggler1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"> </span>
            </button>


            {% else %}
            <div class="collapse navbar-collapse" id="navbarToggler1">
              <ul class="nav navbar-nav navbar-right ml-auto">
                <li ><a href="{{url_for('users.login')}}" class="nav-link mx-1">Login</a></li>
                <li><a href="{{url_for('users.register')}}" class="nav-link mx-1">Register</a></li>
              </ul>
            </div>
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler1" aria-controls="navbarToggler1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"> </span>
            </button>
            {% endif %}

          </div>
          
        </nav>
    </header>
    <div class="container">
        <div class="row">
          <div class="col-12 col-md-8">
            {% block mainSection %}
            {% endblock mainSection %}
          </div>

          {% if 'user_id' in session.keys()  %}
        <aside class="col-12 col-sm-12 col-md-4 additional">
            
              <!-- Tags Section -->
              <p style="font-size: 150%;font-weight: bold;">Tags You Follow:</p>
              <div class=" mt-2 overflow-auto bg-white rounded-lg p-3" style=" height: 15em;" >
                 
                  {% for tag in Tags %}
                      <div>
                        <a class="text-success" style=" font-size:120%;" href="{{url_for('discussions.TagInfo', tag_id=tag.Tagid)}}">{{tag.Tagtitle}}</a> 
                      </div>      
                  {% endfor %}
              </div> 

              <p style="font-size: 150%;font-weight: bold;">Search For Tags:</p>
              <div class=" mt-2 overflow-auto bg-white rounded-lg p-3" style=" height: 10em;" >
                  <form action="{{url_for('discussions.fetchTags')}}" class="form" id="FetchTags"  method="post">
                      <input type="text" class="form-control" placeholder="Start with #" name="tagname" />
                      <input type="submit" class="form-control btn btn-success mt-2" name="submit" value="Fetch" />       
                      <div class="form-group mt-3 text-danger" >
                        {% with messages=get_flashed_messages() %}
                          {% if messages %}
                            {% for message in messages %}
                              <small>{{message}}</small>
                            {% endfor %}
                          {% endif %}
                        {% endwith %} 
                      </div>             
                  </form>
              </div> 

            </div>
        </aside>
        {% endif %}
        </div>
    </div>


    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
   
  </body>
</html>